using BlogGeneratorApp.Models;

namespace BlogGeneratorApp.Services
{
    public class BlogScheduleService : BackgroundService
    {
        private readonly ILogger<BlogScheduleService> _logger;
        private readonly IServiceProvider _serviceProvider;
        private readonly List<string> _topics;
        private readonly List<string> _categories;
        private Timer _timer;
        private bool _isRunning = false;

        public BlogScheduleService(ILogger<BlogScheduleService> logger, IServiceProvider serviceProvider)
        {
            _logger = logger;
            _serviceProvider = serviceProvider;

            _topics = new List<string>
            {
                "ASP.NET Core MVC Development Best Practices",
                "Entity Framework Core Performance Optimization",
                "Securing Web Applications Against Common Threats",
                "Building Responsive UIs with Bootstrap and Tailwind",
                "Microservices Architecture with .NET",
                "DevOps Practices for .NET Applications",
                "AI Integration in Modern Web Applications"
            };

            _categories = new List<string>
            {
                "Web Development",
                "Database",
                "Security",
                "Frontend",
                "Architecture",
                "DevOps",
                "AI & Machine Learning"
            };
        }

        public void StartScheduling()
        {
            if (_isRunning)
            {
                _logger.LogInformation("Blog scheduling is already active");
                return;
            }

            _isRunning = true;
            _logger.LogInformation("Blog scheduling started");

            _ = GenerateBlogPostAsync();
        }

        public void StopScheduling()
        {
            if (!_isRunning)
            {
                _logger.LogInformation("Blog scheduling is already inactive");
                return;
            }

            _isRunning = false;
            _logger.LogInformation("Blog scheduling stopped");
        }

        protected override Task ExecuteAsync(CancellationToken stoppingToken)
        {
            _timer = new Timer(async _ => await CheckScheduleAsync(), null, TimeSpan.Zero, TimeSpan.FromHours(1));

            return Task.CompletedTask;
        }

        private async Task CheckScheduleAsync()
        {
            if (!_isRunning)
            {
                return;
            }

            try
            {
                var now = DateTime.UtcNow;

                // Check if it's time to post (e.g., 9 AM UTC)
                if (now.Hour == 9 && now.Minute < 15) // Check in a 15-minute window to avoid missing it
                {
                    using (var scope = _serviceProvider.CreateScope())
                    {
                        var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
                        var todayStart = DateTime.UtcNow.Date;
                        var todayEnd = todayStart.AddDays(1);

                        var postedToday = dbContext.Blogs
                            .Any(b => b.IsAutoGenerated && b.CreatedAt >= todayStart && b.CreatedAt < todayEnd);

                        if (!postedToday)
                        {
                            await GenerateBlogPostAsync();
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in blog schedule check");
            }
        }

        private async Task GenerateBlogPostAsync()
        {
            try
            {
                _logger.LogInformation("Generating scheduled blog post");

                // Get today's day of week (0-6, Sunday = 0) to rotate through topics
                int dayOfWeek = (int)DateTime.UtcNow.DayOfWeek;

                string topic = _topics[dayOfWeek % _topics.Count];
                string category = _categories[dayOfWeek % _categories.Count];

                using (var scope = _serviceProvider.CreateScope())
                {
                    var openAIService = scope.ServiceProvider.GetRequiredService<OpenAIService>();
                    var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
                    
                    string blogContent = await openAIService.GenerateBlogContent(topic, category);
                    string blogTitle = await openAIService.GenerateBlogTitle(topic, category);
                    string blogSummary = await openAIService.GenerateBlogSummary(blogContent);

                    var blogPost = new Blog
                    {
                        Title = blogTitle,
                        Summary = blogSummary,
                        Content = blogContent,
                        Category = category,
                        Author = "AI Assistant",
                        CreatedAt = DateTime.UtcNow,
                        IsAutoGenerated = true,
                        IsPublished = true
                    };

                    dbContext.Blogs.Add(blogPost);
                    await dbContext.SaveChangesAsync();

                    _logger.LogInformation("New blog post created: {Title}", blogTitle);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error generating scheduled blog post");
            }
        }

        public override void Dispose()
        {
            _timer?.Dispose();
            base.Dispose();
        }
    }
}
