using BlogGeneratorApp.Models;
using BlogGeneratorApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace BlogGeneratorApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly BlogScheduleService _blogScheduleService;
        private readonly OpenAIService _openAIService;

        public HomeController(
            ILogger<HomeController> logger,
            ApplicationDbContext context,
            BlogScheduleService blogScheduleService,
            OpenAIService openAIService)
        {
            _logger = logger;
            _context = context;
            _blogScheduleService = blogScheduleService;
            _openAIService = openAIService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public async Task<IActionResult> GetAllPosts()
        {
            try
            {
                var blogs = await _context.Blogs
                    .Where(b => b.IsPublished)
                    .OrderByDescending(b => b.CreatedAt)
                    .Select(b => new
                    {
                        id = b.Id,
                        title = b.Title,
                        summary = b.Summary,
                        category = b.Category,
                        author = b.Author,
                        createdAt = b.CreatedAt,
                        isAutoGenerated = b.IsAutoGenerated,
                        viewCount = b.ViewCount
                    })
                    .ToListAsync();

                return Json(blogs);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error occurred while fetching blog posts");
                return StatusCode(500, "An error occurred while fetching blog posts");
            }
        }

        [HttpPost]
        public IActionResult StartAutoPost()
        {
            try
            {
                _blogScheduleService.StartScheduling();
                return Json(new { success = true, message = "Auto posting started successfully" });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error starting auto post");
                return StatusCode(500, "An error occurred while starting auto post");
            }
        }

        [HttpPost]
        public IActionResult StopAutoPost()
        {
            try
            {
                _blogScheduleService.StopScheduling();
                return Json(new { success = true, message = "Auto posting stopped successfully" });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error stopping auto post");
                return StatusCode(500, "An error occurred while stopping auto post");
            }
        }

        [HttpGet]
        public async Task<IActionResult> BlogDetails(int id)
        {
            var blog = await _context.Blogs.FindAsync(id);

            if (blog == null)
            {
                return NotFound();
            }
            blog.ViewCount++;
            await _context.SaveChangesAsync();

            return View(blog);
        }

        [HttpPost]
        public async Task<IActionResult> GenerateTestPost(string topic, string category)
        {
            try
            {
                if (string.IsNullOrEmpty(topic) || string.IsNullOrEmpty(category))
                {
                    return BadRequest("Topic and category are required");
                }

                string blogContent = await _openAIService.GenerateBlogContent(topic, category);
                string blogTitle = await _openAIService.GenerateBlogTitle(topic, category);
                string blogSummary = await _openAIService.GenerateBlogSummary(blogContent);

                var blogPost = new Blog
                {
                    Title = blogTitle,
                    Summary = blogSummary,
                    Content = blogContent,
                    Category = category,
                    Author = "AI Assistant (Test)",
                    CreatedAt = DateTime.UtcNow,
                    IsAutoGenerated = true,
                    IsPublished = true
                };

                _context.Blogs.Add(blogPost);
                await _context.SaveChangesAsync();

                return Json(new
                {
                    success = true,
                    message = "Test blog post created successfully",
                    postId = blogPost.Id,
                    title = blogPost.Title
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error generating test blog post");
                return StatusCode(500, "An error occurred while generating test blog post");
            }
        }
    }
}
