using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace BlogGeneratorApp.Models
{
    public class Blog
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(200)]
        public string? Title { get; set; }

        [Required]
        [StringLength(500)]
        public string? Summary { get; set; }

        [Required]
        public string? Content { get; set; }

        [StringLength(100)]
        public string? Category { get; set; }

        [StringLength(100)]
        public string? Author { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        public DateTime? UpdatedAt { get; set; }

        public bool IsAutoGenerated { get; set; } = false;

        [StringLength(255)]
        public string? FeaturedImageUrl { get; set; }

        public bool IsPublished { get; set; } = true;

        [Range(0, int.MaxValue)]
        public int ViewCount { get; set; } = 0;

        [NotMapped]
        public int CommentCount { get; set; } = 0;
    }
}